- name: variables
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    Duration: "120 Hrs"
  tasks:
   - name: print variables
     ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} and duration is {{ Duration }}"   

