- name: variables
  hosts: web
  vars: # play level avrs
    COURSE: "DevOps with AWS"
    Duration: "120 Hrs"
  tasks:  
   - name: print variables
     ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} and duration is {{ Duration }}"   

       
   - name: print variables
     vars: # Task level vars
      COURSE: "Azure"
     ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} and duration is {{ Duration }}" 


