- name: vars from prompt
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: Please enter the course name
      private: false
    - name: Duration
      prompt: please enter the duration
      private: false
  tasks:
  - name: vars from prompt
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE}} and duration is {{ Duration }}"