- name: Conditions
  hosts: local
  connection: local
  # vars:
  #   i: 20
  vars_prompt:
    name: Number
    prompt: Please enter the number
    private: false
  tasks:
  - name: print the number if the number is greater than 10
    ansible.builtin.debug:
      msg: "Number {{Number}} is greater than 10"
    when: Number  > 10

  - name: print the number if the number is less than 10
    ansible.builtin.debug:
      msg: "Number {{Number}} is less than 10"
    when: Number  < 10