- name: User creation
  hosts: web
  become: yes
  tasks:
  - name: User creation
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: Print user information
    ansible.builtin.debug:
      msg: "User info {{user}}"