- name: gather facts
  hosts: web
  tasks:
  - name: gather facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"

  - name: install nginx when OS is RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx when OS is Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Apt"