- name: filters
  hosts: local
  connection: local
  # vars:
  #   value: "Ramesh"
  tasks:
  - name: filters
    ansible.builtin.debug:
      msg: "Hello {{value | default( 'Krishna') }}"

  - name: convert to lower case
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | lower }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"