- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0809776e60d419e65"
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-00a049b8461501cec"
    zone_id: "narne.shop"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: ec2 resource creation
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: t2.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"

  - name: r53 record creation
    amazon.aws.route53:
      state: present
      zone: "{{zone_id}}"
      record: "{{item.item}}.{{zone_id}}"
      type: A
      ttl: 1
      wait: true
      value: "{{item.instances[0].private_ip_address}}"
      overwrite: true
    loop: "{{ec2_instances.results}}"